import { ReactNode } from "react"
import { Inter } from 'next/font/google'
import Header from "@/components/Header"

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter'
})

export const metadata = {
  title: 'Summary | AI',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter overflow-hidden flex flex-col`}>
        <Header />

        {children}
      </body>
    </html>
  )
}
