import './globals.css'
import { ReactNode } from "react"
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-inter'
})

export const metadata = {
  title: 'Luna | AI',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className={`${inter.variable} bg-zinc-800 font-inter flex flex-col divide-y divide-zinc-700 overflow-hidden`}>
        <Header />

        <main className='w-screen h-screen flex px-4 py-4'>
          {children}
        </main>
      </body>
    </html>
  )
}
