'use client'
import './globals.css'
import { ReactNode } from "react"
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { TranscriptionProvider } from '@/contexts/Transcription'

const inter = Inter({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-inter'
})

export const metadata = {
  title: 'Luna | AI',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter flex flex-col divide-y divide-zinc-100 overflow-hidden`}>
        <Header />

        <main className='w-screen h-screen flex px-4 py-8'>
          <TranscriptionProvider>
            {children}
          </TranscriptionProvider>
        </main>
      </body>
    </html>
  )
}
